### ISSUE TITLE
Joining two datatables

### ISSUE THREAD

**Issue by bhardwajrajesh** [NArnott/System.Linq.Dynamic#12]
Hello,
I am trying to join two datatables, but not clear about the syntax. Can you please provide a sample.

var dt = new DataTable();
            dt.Columns.Add("C1", typeof(int));
            dt.Columns.Add("C2", typeof(string));
            dt.Columns.Add("C3", typeof(string));

            dt.Rows.Add(1, "1", "1");
            dt.Rows.Add(1, "1", "2");
            dt.Rows.Add(1, "2", "2");

            var dt2 = new DataTable();
            dt2.Columns.Add("C11", typeof(int));
            dt2.Columns.Add("C22", typeof(string));
            dt2.Columns.Add("C33", typeof(string));

            dt2.Rows.Add(1, "1", "1");
            dt2.Rows.Add(1, "1", "2");
            dt2.Rows.Add(1, "2", "2");
            var kp = dt2.AsEnumerable()
           .AsQueryable();
            var output1 = dt.AsEnumerable()
           .AsQueryable().Join(kp, "new (it[\"C1\"] as c1, it[\"C2\"] as c2 )", "new(root[\"C11\"] as c1,it[\"C22\"] as c2)",

                "new(it[\"C1\"] as C1, it[\"C2\"] as C2)").ToDynamicArray();

regards

**Comment by NArnott** [comment]
Are you able to perform what you want using standard LINQ?  Please provide the working standard LINQ code, and I should be able to convert it for you.
