### ISSUE TITLE
Aggregate support

### ISSUE THREAD

**Issue by joepwijers** [NArnott/System.Linq.Dynamic#16]
Hi,

Great work this library!

I missed some more aggregate support though when putting it to work for me.
- there is Sum, but not Avg and Count (which I would think are almost copies of Sum support)
- and Sum doesn't work on the full data set, only after adding a GroupBy (like also reported by someone else as well)

Joep

**Comment by StefH** [comment]
**Sum** and **Average** work fine, but only when using a GroupBy. See also my comment on my [question](https://github.com/NArnott/System.Linq.Dynamic/issues/15).

I did add some more unit tests, see my [forked](https://github.com/StefH/System.Linq.Dynamic) project.

About **Count**, I didn't yet check this.

**Comment by NArnott** [comment]
@joepwijers, If you provide a specific example, I can provide you the correct syntax or update the project to include them.  Aggregates should work though, and several of them do.

**Comment by joepwijers** [comment]
Sorry Nathan for not getting back to you before.

Indeed I have now gotten it to work for Sum and Average.

My initial problem was that I was using Avg instead.


I am still using group by 1 to take aggregates on data that is not grouped though.

Is that still needed?






Sent from Surface





From: Nathan Arnott
Sent: ‎Wednesday‎, ‎April‎ ‎1‎, ‎2015 ‎14‎:‎57
To: NArnott/System.Linq.Dynamic
Cc: Joep Wijers





@joepwijers, If you provide a specific example, I can provide you the correct syntax or update the project to include them. Aggregates should work though, and several of them do.

**Comment by NArnott** [comment]
No problem.  As I understand it, there was never a requirement to use the Group by 1 method suggested by StefH.  Please see my response to his [question][0]. 

The rule of thumb is, always do your linq statements in standard form first, and then translate it to dynamic linq.  In this case, there is no need for an extra group by in standard form, so there is no need for it in dynamic linq.

If you still have questions about this, feel free.

[0]: https://github.com/NArnott/System.Linq.Dynamic/issues/15
