### ISSUE TITLE
An unhandled exception of type 'System.Reflection.ReflectionTypeLoadException' 

### ISSUE THREAD

**Issue by MRYingLEE** [NArnott/System.Linq.Dynamic#17]
I met an exception:

An unhandled exception of type 'System.Reflection.ReflectionTypeLoadException' occurred in mscorlib.dll

when I ran the following code:

            List<int> range = new List<int> { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
            IEnumerable rangeResult = range.AsQueryable().Select("it * it");

If I referred some assemblies. 

I found the exception happened in the method:

       static IEnumerable<Type> FindTypesMarkedWithAttribute()
        {
            return AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(x => x.GetTypes())
                .Where(x => x.GetCustomAttributes(typeof(DynamicLinqTypeAttribute), false).Any());
        }

A sample project with the DLLs could be download at 
https://drive.google.com/file/d/0B0CNjRB_2n1GN0xCdk5NMW9UMnM/view?usp=sharing 

Please check.

**Comment by StefH** [comment]
You are probably missing the 'FluentValidationNA.dll'

The best way to use the System.Linq.Dynamic.Library is bu using NuGet, in that way the dependency on FluentValidationNA is automatically resolved.

![ng](https://cloud.githubusercontent.com/assets/249938/6381394/260a430c-bd41-11e4-841f-3b01c8e7ba25.png)

**Comment by MRYingLEE** [comment]
Thank you for your prompt response.

1. I strictly followed your suggestion, but the problem still existed. I
prepared another test project file:


https://drive.google.com/file/d/0B0CNjRB_2n1Gb3RTQ0ZXc3h2bzA/view?usp=sharing


Please check. Please note the problems happened in the following statement:

       static IEnumerable<Type> FindTypesMarkedWithAttribute()

        {

            return AppDomain.CurrentDomain.GetAssemblies()

                .SelectMany(x => x.GetTypes())

                .Where(x =>
x.GetCustomAttributes(typeof(DynamicLinqTypeAttribute), false).Any());

        }


2. I have a question. I let end user to define calculated column at run
time. But sometimes they may make a mistake on syntax of dynamic LINQ. I
validate the syntax by running query. But it is too late  to notify end
users.

Do you have any suggestions to validate dynamic LINQ asap? Of course, some
syntax maybe ORM dependent, so a good syntax doesn't mean working any time.


3. Users may use simple syntax , such as today()>'2015/01/23'. Do you have
tolerance on this, just like a post suggested:

https://stackoverflow.com/questions/24207475/validate-and-modify-string-passed-to-dynamic-linq



4.  Sometimes it's not easy to write dynamic LINQ. Do you have a utility
function to convert a common LINQ express tree to dynamic LINQ? It's a
reverse process for dynamic LINQ.



I am evaluating your package and expect to migrate a project on it.



Thank you in advance,


Ying

**Comment by StefH** [comment]
For question 1]
It works fine on my system. (I'm using VS2013 on a x64 windows)
![debug_ok](https://cloud.githubusercontent.com/assets/249938/6408948/e8373a68-be5c-11e4-883b-3239d8b90f63.png)

**Comment by MRYingLEE** [comment]
If I didn't add the 2 DLLs from DevExpress as references, everything works
fine in my system also.

I tried to trace and found the error happened when your assembly to
traverse all assemblies.

       static IEnumerable<Type> FindTypesMarkedWithAttribute()

        {

            return AppDomain.CurrentDomain.GetAssemblies()

                .SelectMany(x => x.GetTypes())

                .Where(x =>
x.GetCustomAttributes(typeof(DynamicLinqTypeAttribute), false).Any());

        }


To reproduce the exception, you have to add the 2 DLLs from DevExpress as
references.



Regards,

Mr. Ying LEE
----------------------------------------------------------
Remember. Let go. Move on.

**Comment by MRYingLEE** [comment]
BTW, I ran VS 2013 on X64 also.

I guess the exception comes from some assembly conflicts, but I have no
clear idea.



Regards,

Mr. Ying LEE
----------------------------------------------------------
Remember. Let go. Move on.

**Comment by MRYingLEE** [comment]
I knew the reason that caused the problem just now by debugging. When your
code traverse assemblies, an assembly of a specific version was missed. I
still couldn't fix it now for maybe 2 different versions of a same assembly
have been indirectly referred by 3rd party vendors.

So the problem has no direct relation with your code. But I am wondering
whether it is necessary for you to traverse all assemblies, which costs a
lot of time also.

I will input my comment into GitHub.

Please reply my other questions.

Thank you in advance,






Regards,

Mr. Ying LEE
----------------------------------------------------------
Remember. Let go. Move on.

**Comment by NArnott** [comment]
@MRYingLEE, All assemblies must be searched in order to find all possible types marked with the `DynamicLinqTypeAttribute` attribute. 

As for speed, this call is ever only made once (order of  N(1)) per AppDomain, so it's not costly at all.

**Comment by NArnott** [comment]
One more note.  This is the default implementation of `IDynamicLinkCustomTypeProvider` (`DefaultDynamicLinqCustomTypeProvider`).  If you want to implement your own, you can set it using the `GlobalConfig.CustomTypeProvider` property.

**Comment by MRYingLEE** [comment]
Thanks.



Regards,

Mr. Ying LEE
----------------------------------------------------------
Remember. Let go. Move on.
