### ISSUE TITLE
Operator '*' incompatible with operand types 'Single' and 'Decimal'

### ISSUE THREAD

**Issue by MRYingLEE** [NArnott/System.Linq.Dynamic#18]
When the following statement was executed:
       Select("it.floatProp*it.decimalProp")

One exception happened:
         An unhandled exception of type 'System.Linq.Dynamic.ParseException' occurred in System.Linq.Dynamic.dll. Additional information: Operator '*' incompatible with operand types 'Single' and 'Decimal' Operator '*' incompatible with operand types 'Single' and 'Decimal'.

I know it is because the strong type of LINQ.

For you mentioned:
Conversions--The following conversions are implicitly performed by the expression language:
From a numeric type to another numeric type with greater range.

So I just wonder this is a bug in implementation.

If not, can you improve the code to support such a kind of implicit type conversion.

Thank you in advance,

Ying

**Comment by MRYingLEE** [comment]
Sorry to urge you.

Your project has some amazing features (such as type implicit conversion) beyond the original Dynamic LINQ. And I am thinking to immigrate my code to yours from the original.

Please clarify what I met.

Thank you in advance,

Ying

**Comment by NArnott** [comment]
The "up-casting" does occur for certain types, such as Int16 and Int32.  However, Float and Decimal are not compatible.  Try this example, which will fail in direct c# code:

    float x = 1;
    decimal y = 1;
    var result = x * y;

This code will fail.  The same will fail when Dynamic Linq tries to parse it.  The solution in c# and standard linq would be to cast it: `var result = (decimal)x * y`.  

In Dynamic Linq, you need to do the same thing, though the syntax is a bit different:

    .Select("Decimal(it.floatProp) * it.decimalProp")

More details can be found [here][0].

[0]: http://dynamiclinq.azurewebsites.net/Expressions/Type(expr)

**Comment by MRYingLEE** [comment]
I got it. Thank you.

Just wonder I can write an extension to your package or modify your source code so such a kind of situation can be supported by implicit type conversion.

For example, maybe I can use a type table to describe how to deal with  implicit type conversion for 2 different types.

Is it possible? If so, I will work on it.

Thank you again.

**Comment by NArnott** [comment]
If you want to fork your own branch and make those updates, feel free.  If you want to incorporate your changes into this project, request it, and I'll review it at that point.
