### ISSUE TITLE
IN and nullable types

### ISSUE THREAD

**Issue by jenscski** [NArnott/System.Linq.Dynamic#19]
Hello, I have problem with using dynamic IN. E.g.

I have a class something like this.

```cs
class MyClass
{
    public int ID {get;set;}
   public int? SomeProperty {get;set;}
}
```

When I try to do a IN query on ID, it works, but on SomeProperty, it wont work
```cs
data.Where("ID IN (1,2)") => works
data.Where("SomeProperty IN (1,2)") => System.Linq.Dynamic.ParseException("Expression of type 'System.Nullable`1[System.Int32]' expected")
```

I have tried to understand the code behind the functionality, but it's way over my head.

Is this possibly in to achieve in any way?

---
Jens-Christian

**Comment by NArnott** [comment]
I'll have to look into this.  It doesn't look like I've considered this case.

For now, try using this construct:

    var values = new int?[] { 1, 2 };
    data.Where("SomeProperty in @0", values);

Let me know if that works for you.

**Comment by jenscski** [comment]
Ok, thanks. Unfortunately I'm building the where string dynamically, so a parameter is a little hard.

But I can do (SomeProperty == 1 || SomeProperty  == 2), so there is a way around.

**Comment by NArnott** [comment]
This bug has been fixed in this [commit][0].  It will be in the next release.

[0]: https://github.com/NArnott/System.Linq.Dynamic/commit/9c1816a2cddd4727e0c0eaa7c402fb1a441dbc43
