### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dradovic** [NArnott/System.Linq.Dynamic#22]
Under what license is the library published?

**Comment by meatGUY** [comment]
If I am not mistaken is MSPL

**Comment by dradovic** [comment]
Would be really cool to have an official LICENSE file committed along.

**Comment by NArnott** [comment]
It is under MSPL. If there is one thing I'm not all that familiar with is the open source licensing options, so I'm always behind on that.  Anyways, there was a pull request that I merged that included the license file, so it's there now.
